### ISSUE TITLE
specific webiste latin-like letters appear as garbled

### ISSUE THREAD

**Issue by Rupthya** [webrecorder/archiveweb.page#20] opened 2021-03-10 03:03 UTC
I'm facing a problem when saving website from taobao.com (Simplified Chinese)

here is a sample link:
https://item.taobao.com/item.htm?id=585231745608

The left side of picture show below is correct one (normal view) and right side is the garbled one (archive by extension).
![example](https://i.imgur.com/hTvd215.png)

I think it is the website problem rather than the extension encoding, saving properly with Traditional Chinese / Japan / Korean from other website.

Also thank you for hard work this tool save my life.

***

I found new sample that causing the same issue. (Japanese text)

https://www.hmv.co.jp/artist_きまぐれオレンジ-ロード_000000000548287/item_きまぐれオレンジ☆ロード-あの日にかえりたい-【初回生産限定盤】-ピンク・カラーヴァイナル仕様-アナログレコード_11521901

**Comment by ikreymer** [comment] 2021-03-26 16:05
Thanks, this should now be fixed in 0.5.13 extension + app! Caused by wabac.js not handling non-UTF-8 encodings correctly.

**Closed by ikreymer** 2021-03-26 16:05 UTC
