### ISSUE TITLE
archiveweb replay with local wacz files does not work since last release

### ISSUE THREAD

**Issue by dteyssou** [webrecorder/archiveweb.page#178] opened 2023-08-16 14:24 UTC
Since last release (0.11.1), it does not seem possible to replay and check in the extension that the archived page is properly saved. Instead, we get a grey page (FB) or a logo (Instagram) while sending those resulting warcz files to the Wayback machine still work (and the Wayback machine can display them).

**Comment by ikreymer** [comment] 2023-08-17 01:49
Looks like the issue is in replayweb.page due to some updates to wabac.js -- was able to repro with instagram replay.

**Comment by ikreymer** [comment] 2023-08-17 05:33
Will be in upcoming release (0.11.2) and RWP (1.8.8), will close when released.

**Comment by ikreymer** [comment] 2023-08-18 01:08
Released in 0.11.2, now out and ReplayWeb.page 1.8.8

**Closed by ikreymer** 2023-08-18 01:08 UTC
