### ISSUE TITLE
Page not fully loading during playback

### ISSUE THREAD

**Issue by halmos** [webrecorder/archiveweb.page#105] opened 2022-10-05 14:54 UTC
Hi,

We are finding an issue with archives of some urls in which the page does not complete loading during playback. The pages that have this issue seem to share many of the same error type reported in the console. Example error below: 
```
wombat.js:1 A preload for 'chrome-extension://fpeoodllldobpkbkabpblcfaogecpndd/replay/w/qsnj6ly31887mhgdild7aw/20221005135750mp_/https://static.xx.fbcdn.net/rsrc-translations.php/v6iosk4/yM/l/en_US/rGAtuS1rzMosi-OvQOy34xStbHGP91bn71TL5KYVsXZpFKOoBDFoprfZ9ciVUsotBJZVocPi6ZMD_0Ie7U8cDy5lngEQMxCm-CfXmTRN1BqGFDOr3Psq0exUn.js?_nc_x=p5yUGoi-03C' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
```

Additionally, we also see 404 errors for ajax POST requests that seem to be for a websocket: 

```
wombat.js:1          POST chrome-extension://fpeoodllldobpkbkabpblcfaogecpndd/replay/w/ya4frf2jskpg67wnapig84/20220930133321mp_/https://edge-chat.facebook.com/mqtt/pull?region=atn&sid=5278408728641535&chunked=true 404 (Not Found)
```

which results in the following network resonpse:
```
This page https://edge-chat.facebook.com/mqtt/pull?region=atn&sid=2254927313240063&chunked=true&__wb_method=POST&u=1498090096&s=2254927313240063&cp=3&ecp=10&chat_on=false&fg=false&d=2e43cfd6-2714-475b-b8e3-14e639f2c07c&ct=websocket&mqtt_sid=&aid=219994525426954&0=/rtc_multi&1=/legacy_web&2=/orca_presence&dc=&no_auto_fg=true&php_override= is not part of this archive.
```

It's difficult to tell if those two errors are related or if the 2nd error is just the page attempting to make ajax requests that are not relevant to the wacz archive. 

The first error seems more likely to be culprit here. What does `request credentials mode` refer to? 

*Sample Urls (Note that you need to be logged-in to FB to test this)*

- https://www.facebook.com/aalisarem/posts/167216991371363
- https://www.facebook.com/story.php?story_fbid=10159067040296125&id=538786124&refid=17&_ft_=mf_story_key.10159067040296125%3Atop_level_post_id.10159067040296125%3Atl_objid.10159067040296125%3Acontent_owner_id_new.538786124%3Athrowback_story_fbid.10159067040296125%3Astory_location.4%3Athid.538786124%3A306061129499414%3A2%3A0%3A1635749999%3A-8681743343883909496%3A%3A

Many thanks for your excellent work on this project.

**Comment by halmos** [comment] 2022-10-18 14:08
This may be related to issue #111

**Comment by ikreymer** [comment] 2024-08-13 02:53
Hard to say what the issue is, but there's been a bunch of improvements, hopefully new captures work better, starting with 0.12.6. Closing for now as we don't have much to repro. (The edge-chat errors can generally be ignored and are related to chat - recommend turning off live messaging when archiving)

**Closed by ikreymer** 2024-08-13 02:53 UTC
